<?php

namespace App\Enums;
use Filament\Support\Contracts\HasLabel;

enum AbuyogBarangay: string implements HasLabel {
    case Alangilan = 'alangilan';
    case Anibongon = 'anibongon';
    case Bagacay = 'bagacay';
    case Bahay = 'bahay';
    case Balinsasayao = 'balinsasayao';
    case Balocawe = 'balocawe';
    case Balocawehay = 'balocawehay';
    case Barayong = 'barayong';
    case Bayabas = 'bayabas';
    case Bito = 'bito';
    case Buaya = 'buaya';
    case Buenavista = 'buenavista';
    case Bulak = 'bulak';
    case Bunga = 'bunga';
    case Buntay  = 'buntay';
    case Burubud_an = 'burubud_an';
    case Cadac_an = 'cadac_an';
    case Cagbolo  = 'cagbolo';
    case Can_aporong = 'can_aporong';
    case Can_uguib = 'can_uguib';
    case Canmarating = 'canmarating';
    case Capilian = 'capilian';
    case Combis = 'combis';
    case Dingle = 'dingle';
    case Guintagbucan = 'guintagbucan';
    case Hampipila = 'hampipila';
    case Katipunan  = 'katipunan';
    case Kikilo = 'kikilo';
    case Laray = 'laray';
    case Lawaan = 'lawaan';
    case Libertad = 'libertad';
    case Loyonsawang = 'loyonsawang';
    case Mag_atubang = 'mag_atubang';
    case Mahagna = 'mahagna';
    case Mahayahay = 'mahayahay';
    case Maitum = 'maitum';
    case Malaguicay = 'malaguicay';
    case Matagnao = 'matagnao';
    case Nalibunan = 'nalibunan';
    case Nebga = 'nebga';
    case New_Taligue = 'new_Taligue';
    case Odiongan = 'odiongan';
    case Old_Taligue = 'old_taligue';
    case Pagsang_an = 'pagsang_an';
    case Paguite = 'paguite';
    case Parasanon = 'parasanon';
    case Picas_Sur = 'picas_sur';
    case Pilar = 'pilar';
    case Pinamanagan = 'pinamanagan';
    case Salvacion = 'salvacion';
    case San_Francisco = 'san_francisco';
    case San_Isidro = 'san_isidro';
    case San_Roque = 'san_roque';
    case Sta_Fe = 'sta_fe';
    case Sta_Lucia = 'sta_lucia';
    case Sto_Nino = 'sto_nino';
    case Tabigue = 'tabigue';
    case Tadoc = 'tadoc';
    case Tib_o = 'tib_o';
    case Tinalian = 'tinalian';
    case Tinocolan = 'tinocolan';
    case Tuy_a = 'tuy_a';
    case Victory = 'victory';
    public function getLabel(): string {
        return match ($this) {
            self::Alangilan => 'ALANGILAN',
            self::Anibongon => 'ANIBONGON',
            self::Bagacay => 'BAGACAY',
            self::Bahay => 'BAHAY',
            self::Balinsasayao => 'BALINSASAYAO',
            self::Balocawe => 'BALOCAWE',
            self::Balocawehay => 'BALOCAWEHAY',
            self::Barayong => 'BARAYONG',
            self::Bayabas => 'BAYABAS',
            self::Bito => 'BITO',
            self::Buaya => 'BUAYA',
            self::Buenavista => 'BUENAVISTA',
            self::Bulak => 'BULAK',
            self::Bunga => 'BUNGA',
            self::Buntay  => 'BUNTAY',
            self::Burubud_an => 'BURUBUD-AN',
            self::Cadac_an => 'CADAC-AN',
            self::Cagbolo  => 'CAGBOLO',
            self::Can_aporong => 'CAN-APORONG',
            self::Can_uguib => 'CAN-UGUIB',
            self::Canmarating => 'CANMARATING',
            self::Capilian => 'CAPILIAN',
            self::Combis => 'COMBIS',
            self::Dingle => 'DINGLE',
            self::Guintagbucan => 'GUINTAGBUCAN',
            self::Hampipila => 'HAMPIPILA',
            self::Katipunan => 'KATIPUNAN',
            self ::Kikilo => 'KIKILO',
            self::Laray => 'LARAY',
            self ::Lawaan => 'LAWAAN',
            self::Libertad => 'LIBERTAD',
            self::Loyonsawang => 'LOYONSAWANG',
            self::Mag_atubang => 'MAG-ATUBANG',
            self::Mahagna => 'MAHAGNA',
            self::Mahayahay => 'MAHAYAHAY',
            self::Maitum => 'MAITUM',
            self::Malaguicay => 'MALAGUICAY',
            self::Matagnao => 'MATAGNAO',
            self::Nalibunan => 'NALIBUNAN',
            self::Nebga => 'NEBGA',
            self::New_Taligue => 'NEW TALIGUE',
            self::Odiongan => 'ODIONGAN',
            self::Old_Taligue => 'OLD TALIGUE',
            self::Pagsang_an => 'PAGSANG-AN',
            self::Paguite => 'PAGUITE',
            self::Parasanon => 'PARASANON',
            self::Picas_Sur => 'PICAS SUR',
            self::Pilar => 'PILAR',
            self::Pinamanagan => 'PINAMANAGAN',
            self::Salvacion => 'SALVACION',
            self::San_Francisco => 'SAN FRANCISCO',
            self::San_Isidro => 'SAN ISIDRO',
            self::San_Roque => 'SAN ROQUE',
            self::Sta_Fe => 'STA. FE',
            self::Sta_Lucia => 'STA LUCIA',
            self::Sto_Nino => 'STO. NINO',
            self::Tabigue => 'TABIGUE',
            self::Tadoc => 'TADOC',
            self::Tib_o => 'TIB-O',
            self::Tinalian => 'TINALIAN',
            self::Tinocolan => 'TINOCOLAN',
            self::Tuy_a => 'TUY-A',
            self::Victory => 'VICTORY',
        };
    }
}
